server:
  port: 8080
spring:
  application:
    name: gateway-service
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/tfg-siglo21-db
      auto-index-creation: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth-user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/users/auth/**
        - id: auth-user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/users
            - Method=POST
        - id: auth-user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/users/recovery
        - id: auth-user-service
          uri: http://localhost:8001
          predicates:
            - Path=/api/v1/users/**
          filters:
            - AuthFilter
        - id: graph-service
          uri: http://localhost:8002
          predicates:
            - Path=/api/v1/**
          filters:
            - AuthFilter